### ISSUE TITLE
issue with Makefile for docker run command

### ISSUE THREAD

**Issue by benkeser** [laurvana/DATA550_Final_Project#5]
Please review hints on canvas. Will regrade when this issue is closed.

**Comment by laurvana** [comment]
Is the report not generating? I am not sure what I missing from the final project 8 guidelines on CANVAS.

**Comment by benkeser** [comment]
Your [docker run command](https://github.com/laurvana/DATA550_Final_Project/blob/485f5ab8786ab56da0e87bb8e267a79a7e7ff216/Makefile#L34) needs to reference your image name by its docker hub tag.

**Comment by laurvana** [comment]
Aha! I have updated the make command to reflect this change. Thank you!!
